### ISSUE TITLE
Patch file found for package node-abi which is not present at node_modules/node-abi

### ISSUE THREAD

**Issue by kamal0808** [thiagoelg/node-printer#40]
I am receiving this error with `npm install` on linux.

`Patch file found for package node-abi which is not present at node_modules/node-abi`

Here's the full output
```
> node-gyp-build
> @thiagoelg/node-printer@0.5.7 install /builds/billmobi/desktop-app-electronjs/node_modules/@thiagoelg/node-printer
> prebuild-install || node-gyp rebuild
> @thiagoelg/node-printer@0.5.7 postinstall /builds/billmobi/desktop-app-electronjs/node_modules/@thiagoelg/node-printer
> patch-package
patch-package 6.4.7
Applying patches...
Error: Patch file found for package node-abi which is not present at node_modules/node-abi
---
patch-package finished with 1 error(s).
```

This is my environment:
docker image: electronuserland/builder:wine
link: https://hub.docker.com/layers/electronuserland/builder/wine/images/sha256-2f985d6d571a749c89198862d01aaeb8b5703c1faf4bc6b1a877e8e4dc4afce3?context=explore

Node version: `v14.17.0`

We are unable to create new builds because of this. Can you help?

Note: I tried installing node-abi separately first, didn't help.

**Comment by thiagoelg** [comment]
Hey, I've just released version `0.6.1`, can you try it and let me know if it's fixed?

**Comment by kamal0808** [comment]
Hey, thanks for getting on this promptly. I tried running this, I can still see the same issue.

**Comment by thiagoelg** [comment]
Apparently, it's not recommended to patch-packages in a published library, I'll revert and should a new version soon, thanks!

**Comment by thiagoelg** [comment]
@kamal0808 hopefully `0.6.2` fixes this!
`patch-packages` should not run anymore, let me know if it's still broken.

**Comment by kamal0808** [comment]
Hey @thiagoelg, I will be able to test this out in some days. Sorry for not working on this promptly. I appreciate your hard work in this. Thanks. Will update the results here soon.
